### ISSUE TITLE
Execution Fails in Windows 7

### ISSUE THREAD

**Issue by severak** [cretz/doogie#48]
Doogie dies immediately with error level 2 if ran by this batch script:

```
doogie
echo %ERRORLEVEL%
pause
```

My computer runs Windows 7 Home Premium 64-bit SP1.

**Comment by cretz** [comment]
I will look into this shortly, thanks for the bug report.

**Comment by cretz** [comment]
@severak and @CJKinni, I just tagged a new release where I embedded a few more resources at https://github.com/cretz/doogie/releases/tag/v0.6.1. Can you please try that and confirm it still does not work?

I do build this on Windows 8.1 pro but it's standard VS 2015. If it still doesn't work, can anyone that wants to help clone the repo and [build](https://cretz.github.io/doogie/guide/develop#building) it yourself and maybe show the debug output or help debug on Win 7?

**Comment by CJKinni** [comment]
This is now working for me on Windows 10 (I was having the same issue on v0.6.0)

**Comment by cretz** [comment]
Cool, closing. Comments are still unlocked though if problems persist.
