### ISSUE TITLE
Unable to Save with Some Block Lists

### ISSUE THREAD

**Issue by terinjokes** [cretz/doogie#55]
Using Doogie 0.6.1, I'm unable to save the profile's preferences for some lists. I've noticed that when a list fails to populate the name, homepage, and expiration policy in the UI, the preferences won't save.

For example, while [EasyList][el] works, [Peter Lowe's List][pll] and the [Estonian Ad-block list][est]  do not.

[el]: https://easylist.to/easylist/easylist.txt
[pll]: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
[est]: https://adblock.ee/list.php

**Comment by cretz** [comment]
Thanks for the report. Will fix. Dumb thing on my part:

    Failed to exec query:  "NOT NULL constraint failed: blocker_list.name Unable to fetch row"

Not sure why I'm not using an empty string here. I need to set these default values in the constructor of the BlockerList.
