### ISSUE TITLE
Hard Refresh

### ISSUE THREAD

**Issue by tfont** [cretz/doogie#62]
_Control + R_

Not sure if the normal refresh contains a hard refresh or not... Looks like it does at automatically does at the moment...

_Reference:_
- https://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome
- https://wiki.scratch.mit.edu/wiki/Help:Hard_Refresh

**Comment by cretz** [comment]
Please reference the user guide at https://cretz.github.io/doogie/guide/browser:

> When there is not a page loading, there is a refresh button to the right of the address bar. Pressing this button will refresh the page, utilizing the cache if available. This can also be triggered via F5. Pressing Ctrl while clicking the button, pressing Ctrl+F5, or pressing Ctrl+R will do a refresh without utilizing the cache (i.e. a full reload).

Is this a bug? is there something that should change? I don't understand what the suggestion is here.

**Comment by tfont** [comment]
Ah! I had no idea the Ctrl+R was working. Doesn't seem like a bug. I just wasn't able to confirm it' functionality. Thanks!
